config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about',  to: 'homes#about', as: :about
  resources :users, only:[:show, :edit, :update]
  get 'users', to: 'users#index', as: :users
  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/20200501_noimage.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :email, uniqueness: true
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:edit, :show, :index]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book= Book.find(params[:id])
    if @book.user_id != current_user.id
        redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @books = @user.books.order('updated_at DESC')
  end

  def edit
     @user = User.find(params[:id])
      if @user != current_user
        redirect_to user_path(current_user.id)
      end

  end

  def index
    @user = current_user
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
        <div class= "errors_explanation">
          <h4><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h4>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
             <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= form_with model: @book do |f| %>
      <div class= "form_group mb-3">
        <%= f.label :title %>
        <%= f.text_field :title, class:"form-control", autofocus: true %>
      </div>
      <div class= "form_group mb-3">
        <%= f.label :opinion %></br>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class= "form_group mb-3">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>

    <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= flash[:notice] %>
  <% if @book.errors.any? %>
   <div class= "errors_explanation">
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
   </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
                <td><%= link_to image_tag(book.user.get_profile_image(80,80)), user_path(book.user) %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class= "table">
        <tr>
          <td><%= image_tag @user.get_profile_image(100,100) %></br><%=link_to @user.name, user_path(@user.id) %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
        <% if @user ==  current_user %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-success' %></td>
          <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, class: 'btn btn-danger',  "data-confirm" => "本当に消しますか?" %></td>
        <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
    <div class="row">
      <div class="mx-auto">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row mb-3">
              <a class="btn btn-info btn-block" type="button" href="/users/sign_in/">Log in</a>
            </div>
            <div class="row">
              <a class="btn btn-success btn-block" type="button" href="/users/sign_up">Sign up</a>
            </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: "nav-link text-white" do %>
                <i class="fas fa-home" style="color:#fff;"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link text-white" do %>
                <i class="fas fa-users" style="color:#fff;"></i> Users
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path, class: "nav-link text-white" do %>
                <i class="fas fa-book-open" style="color:#fff;"></i> Books
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-white" do %>
                <i class="fas fa-sign-out-alt" style="color:#fff;"></i> Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link text-white" do %>
                <i class="fas fa-home" style="color:#fff;"></i> Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: "nav-link text-white" do %>
                <i class="fas fa-link" style="color:#fff;"></i> About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: "nav-link text-white" do %>
                <i class="fas fa-user-plus" style="color:#fff;"></i> Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: "nav-link text-white" do %>
                <i class="fas fa-sign-in-alt" style="color:#fff;"></i> Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div  class="mx-auto">
            <h6>CopyRight Infratop.inc</h6>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User Info</h2>
<%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
   <tr><th>name</th><td><strong><%= user.name %></strong></td></tr>
   <tr><th>introduction</th><td><strong><%= user.introduction %></strong></td></tr>
  </table>
<div class= "row">
  <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

<h2>New book</h2>
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title, class:"form-control" %>

  <h4>Opinion</h4>
  <%= f.text_area :body, class:"form-control" %>

　</br><%= f.submit class: 'btn btn-success' %>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <div class= "errors_explanation">
          <h4><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h4>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
             <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @user do |f| %>
      <div class= "form_group">
        <%= f.label :name %>
        <%= f.text_field :name, class:"form-control", autofocus: true %>
      </div>
      <div class= "form_group mt-3">
        <%= f.label :image %></br>
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div class= "form_group mt-3">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class:"form-control" %>
      </div>
      <div class= "form_group mt-3">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
    <h1>Users</h1>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
                <td><%= image_tag user.get_profile_image(80,80) %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
                <td><%= link_to image_tag(book.user.get_profile_image(80,80)), user_path(book.user) %></td>
                <td><%= link_to book.title, book_path(book.id) %></td>
                <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>